In [2]:
import numpy as np

In [7]:
# persons = np.array([10, 20, 38,42, 54, 80])
persons = np.array([1, 2, 3,4,5, 6])
m = np.mean(persons)
n = len(persons)
print(m)
d = (persons-m)/n
d

3.5


array([-0.41666667, -0.25      , -0.08333333,  0.08333333,  0.25      ,
        0.41666667])

In [11]:
a = np.zeros((n,n))
for i in range(n):
    for j in range(i, n):
        a[i,j] = d[j] - d[i]
        a[j,i] = -a[i,j]
    a[i,i] = 0
np.round(a,2)

array([[ 0.  ,  0.17,  0.33,  0.5 ,  0.67,  0.83],
       [-0.17,  0.  ,  0.17,  0.33,  0.5 ,  0.67],
       [-0.33, -0.17,  0.  ,  0.17,  0.33,  0.5 ],
       [-0.5 , -0.33, -0.17,  0.  ,  0.17,  0.33],
       [-0.67, -0.5 , -0.33, -0.17,  0.  ,  0.17],
       [-0.83, -0.67, -0.5 , -0.33, -0.17,  0.  ]])

In [12]:
# b = np.zeros((n, n))
# b[0] = a[0].copy()
b = a.copy()
for i in range(n):
#     b[i] = a[i].copy()
    neg_el = b[i] < 0
    pos_el = b[i] > 0
    sum_neg_abs = -b[i][neg_el].sum()
    sum_pos = b[i][pos_el].sum()
    
    if sum_neg_abs < sum_pos:
        bad_el = neg_el
        good_el = pos_el
        bad_sum = sum_neg_abs
    else:
        bad_el = pos_el
        good_el = neg_el
        bad_sum = sum_pos
        
    sign = np.sign(b[i][good_el])[0]
    b[i][bad_el] = 0
    j = 0
    while bad_sum != 0:
        if good_el[j]:
            diff = bad_sum - sign*(b[i][j])
            b[i][j] = sign*max(0, -diff)
            bad_sum = max(0, diff)
        j += 1
        
np.round(b,2)

array([[ 0.  ,  0.17,  0.33,  0.5 ,  0.67,  0.83],
       [ 0.  ,  0.  ,  0.  ,  0.33,  0.5 ,  0.67],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.5 ],
       [-0.  , -0.33, -0.17,  0.  ,  0.  ,  0.  ],
       [-0.5 , -0.5 , -0.33, -0.17,  0.  ,  0.  ],
       [-0.83, -0.67, -0.5 , -0.33, -0.17,  0.  ]])